name: Checkstyle

on:
  push:
    branches:
      - main
      - mlk/approval_testing_stuff

jobs:
  checkstyle-on-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: checkstyle::checkstyle
        run: mvn checkstyle:checkstyle # This command runs the Checkstyle plugin

      - name: Copy Checkstyle Report to gh-pages Branch
        run: |
          git fetch origin gh-pages:gh-pages
          git switch gh-pages
          mkdir -p github-pages  # Create destination directory if it doesn't exist
          # ls -lRa | nl
          # 
          cp  target/site/checkstyle.html  github-pages/checkstyle.html 
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add github-pages/checkstyle.html
          if [[ -n $(git status -s) ]]; then
            git commit -m "Update Checkstyle report"
            git push origin gh-pages
          else
            echo "No changes to commit"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Checkstyle Report
        uses: actions/upload-artifact@v2
        with:
          name: checkstyle-report
          path: target/site/checkstyle.html # Default path for Checkstyle report generated by Maven

      
